// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"learngo/dependency_injection/pkg"
)

// Injectors from wire.go:

func InitializeEvent(phrase string) (pkg.Event, error) {
	message := pkg.NewMessage(phrase)
	greeter := pkg.NewGreeter(message)
	event, err := pkg.NewEvent(greeter)
	if err != nil {
		return pkg.Event{}, err
	}
	return event, nil
}
